language: generic

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: true
      before_install:
        - sudo apt-get install -y powershell
    - os: osx
      osx_image: xcode9.1
      before_install:
        - brew tap caskroom/cask
        - brew cask install powershell
  fast_finish: true
script:
  - pwsh -f "${env:TRAVIS_BUILD_DIR}/test.ps1"
